# Generated by Django 4.0.4 on 2022-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_book_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
